version: '3.8'

services:
  app_s2next:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: app_s2next
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - s2next_network
  nginx_s2next:
    image: nginx:1.19-alpine
    container_name: nginx_s2next
    restart: always
    ports:
      - "9999:80"
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
    networks:
      - s2next_network
networks:
  s2next_network:

