version: '3.8'
services:
  nginx_s2next:
    container_name: nginx_s2next
    build: './docker/nginx/'
    ports:
      - "8888:80"
    depends_on:
      - mysql_s2next
      - php_s2next
    volumes:
      - ./:/var/www/html
    networks:
      - s2next_network
  mysql_s2next:
    image: mysql:5.7
    container_name: mysql_s2next
    restart: always
    environment:
      MYSQL_DATABASE: 's2next'
      MYSQL_ROOT_PASSWORD: 'gralrodriguez'
      MYSQL_USER: 's2next'
      MYSQL_PASS: 's2next'
    ports:
      - "33080:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - s2next_network
  php_s2next:
    container_name: php_s2next
    build: './docker/php/'
    volumes:
      - ./:/var/www/html
    networks:
      - s2next_network
networks:
  s2next_network:

